# Generated by Django 2.1.2 on 2018-10-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgame', '0003_auto_20181008_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='question',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
