# Generated by Django 2.1.2 on 2018-10-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgame', '0004_auto_20181008_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='qnas',
            new_name='qna',
        ),
    ]
